### ISSUE TITLE
Firefox Sync Server 1.9.1

### ISSUE THREAD

**Issue by ironashram** [dojo90/synology-docker-mozilla-syncserver#8]
Do you have any plan to update this for the latest firefox sync release?

**Comment by dojo90** [comment]
Thank you for your hint! If there is a new version, I will plan to upgrade my docker as well 👍

**Comment by boexler** [comment]
The last update didn't work anymore and I am currently unable to get the container up to date with the latest version of the Mozilla repository. However, if you manage to do it, I would be very grateful if you carried out a suitable pull request.

**Comment by ironashram** [comment]
well i managed to get it working for me but lots of room for improvement
https://github.com/ironashram/synology-docker-mozilla-syncserver/commit/66ad579190b5a5f709f9989be1996cf6e61e6f90

**Comment by boexler** [comment]
Hey @ironashram 
I hadn't received notification of your comment and yesterday I read it by chance! Super thank you! I will merge it into my project. 😊👌
